# Generated by Django 5.2.8 on 2025-12-12 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAusencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_empleado', models.CharField(max_length=20, unique=True)),
                ('nombre_completo', models.CharField(max_length=200)),
                ('departamento', models.CharField(choices=[('rrhh', 'Recursos Humanos'), ('it', 'Tecnologia'), ('finanzas', 'Finanzas'), ('operaciones', 'Operaciones'), ('ventas', 'Ventas'), ('otros', 'Otros Departamentos')], max_length=50)),
                ('puesto_trabajo', models.CharField(max_length=100)),
                ('supervisor_directo', models.CharField(max_length=200)),
                ('tipo_ausencia', models.CharField(choices=[('vacaciones', 'Vacaciones'), ('enfermedad', 'Baja Medica'), ('asuntos_personales', 'Asuntos Personales'), ('administrativo', 'Tramite Administrativo')], default='vacaciones', max_length=30)),
                ('fecha_ausencia', models.DateField()),
                ('motivo_detallado', models.TextField()),
                ('correo_contacto', models.EmailField(max_length=254)),
                ('telefono_contacto', models.CharField(max_length=20)),
                ('telefono_emergencia', models.CharField(max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Aprobacion'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=30)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
