# Generated by Django 5.2.8 on 2025-12-13 23:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudausencia',
            name='fecha_ausencia',
        ),
        migrations.AddField(
            model_name='solicitudausencia',
            name='fecha_fin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='solicitudausencia',
            name='fecha_inicio',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='solicitudausencia',
            name='rut',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudausencia',
            name='codigo_empleado',
            field=models.CharField(default='EMP-000', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudausencia',
            name='correo_contacto',
            field=models.EmailField(default='empleado@empresa.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='solicitudausencia',
            name='departamento',
            field=models.CharField(choices=[('rrhh', 'Recursos Humanos'), ('it', 'Tecnologia'), ('finanzas', 'Finanzas'), ('operaciones', 'Operaciones'), ('ventas', 'Ventas'), ('otros', 'Otros Departamentos')], default='it', max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitudausencia',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitudausencia',
            name='puesto_trabajo',
            field=models.CharField(default='Empleado', max_length=100),
        ),
        migrations.AlterField(
            model_name='solicitudausencia',
            name='supervisor_directo',
            field=models.CharField(default='Supervisor', max_length=200),
        ),
        migrations.AlterField(
            model_name='solicitudausencia',
            name='telefono_emergencia',
            field=models.CharField(default='000000000', max_length=20),
        ),
    ]
