# Generated by Django 5.2.8 on 2025-12-14 19:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_solicitudausencia_fecha_ausencia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitudausencia',
            name='correo_contacto',
        ),
        migrations.RemoveField(
            model_name='solicitudausencia',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='solicitudausencia',
            name='fecha_actualizacion',
        ),
        migrations.RemoveField(
            model_name='solicitudausencia',
            name='puesto_trabajo',
        ),
        migrations.RemoveField(
            model_name='solicitudausencia',
            name='rut',
        ),
        migrations.RemoveField(
            model_name='solicitudausencia',
            name='supervisor_directo',
        ),
        migrations.RemoveField(
            model_name='solicitudausencia',
            name='telefono_contacto',
        ),
        migrations.RemoveField(
            model_name='solicitudausencia',
            name='telefono_emergencia',
        ),
        migrations.AlterField(
            model_name='solicitudausencia',
            name='codigo_empleado',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitudausencia',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente', max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudausencia',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudausencia',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudausencia',
            name='tipo_ausencia',
            field=models.CharField(choices=[('vacaciones', 'Vacaciones'), ('medica', 'Licencia Medica'), ('personal', 'Dia Personal')], max_length=20),
        ),
        migrations.AlterField(
            model_name='solicitudausencia',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
