# Generated by Django 5.2.8 on 2025-12-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_solicitudausencia_correo_contacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitudausencia',
            name='url_justificativo',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
